[tool.poetry]
name = "pyxparams"
version = "0.1.0"
description = ""
authors = [
    "Paola Arce <Paola.Arce@smartdatafoundry.com>",
    "Victor Diaz <Victor.Diaz@smartdatafoundry.com>",
    "Nick Radcliffe <Nick.Radcliffe@smartdatafoundry.com>"
]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
tomli = "^2.0.1"
tomli-w = "^1.0.0"

[tool.poetry.group.dev.dependencies]
tdda = "^2.0.9"
pre-commit = "^3.3.1"
black = "^23.3.0"
flake8 = "^6.0.0"
pytest = "^7.3.1"

[tool.black]
line-length = 79
skip-string-normalization = true
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
