name: Bump version, tag and release

on:
  push:
    branches:
      - main

jobs:
  quality:
    runs-on: ubuntu-latest
    permissions: read-all
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']
    steps:
      - name: Fetch repo
        uses: actions/checkout@v3

      - name: Install poetry
        shell: bash
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - name: Configure poetry
        shell: bash
        run: poetry config virtualenvs.in-project true

      - name: Install dependencies
        shell: bash
        run: poetry install

      - name: Linting
        shell: bash
        run: poetry run pre-commit run --all-files

      - name: Run unit tests
        shell: bash
        run: poetry run pytest

  bump-version-tag:
    runs-on: ubuntu-latest
    needs: quality
    permissions:
      contents: write
    steps:
      - name: Fetch repo
        uses: actions/checkout@v3

      - name: Install poetry
        shell: bash
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'poetry'

      - name: Configure poetry
        shell: bash
        run: poetry config virtualenvs.in-project true

      - name: Check poetry lock
        shell: bash
        run: poetry check --lock

      - name: Install dependencies
        shell: bash
        run: poetry install

      - name: Bump version
        shell: bash
        run: poetry version patch

      - name: Get new version after bump
        shell: bash
        run: echo "bumped_version=$(grep 'version' pyproject.toml | cut -d ' ' -f3 | tr -d '"')" >> $GITHUB_ENV

      - name: Update dunder version
        shell: bash
        run: sed -i "/__version__/c\__version__ = '${{ env.bumped_version }}'" tomlparams/__init__.py

      - name: Tag and commit
        shell: bash
        run: |
          git config user.name "githubactions"
          git config user.email "githubactions@github.com"
          git add pyproject.toml
          git add tomlparams/__init__.py
          git commit -m "bump version"
          git tag -a v${{ env.bumped_version }} -m "v${{ env.bumped_version }}"
          git push --follow-tags origin main

  release:
    runs-on: ubuntu-latest
    needs: bump-version-tag
    permissions:
      contents: write
    steps:
      - name: Fetch repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Install poetry
        shell: bash
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'poetry'

      - name: Configure poetry
        shell: bash
        run: |
          poetry config virtualenvs.in-project true
          poetry config pypi-token.pypi  ${{ secrets.pypi_token }}

      - name: Install dependencies
        shell: bash
        run: poetry install

      - name: Build and publish
        shell: bash
        run: poetry publish --build
